/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.zgzhu.rstptoyuvdemo;

public class CData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rtsp_decoderJNI.delete_CData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    rtsp_decoderJNI.CData_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = rtsp_decoderJNI.CData_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setLen(int value) {
    rtsp_decoderJNI.CData_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return rtsp_decoderJNI.CData_len_get(swigCPtr, this);
  }

  public CData() {
    this(rtsp_decoderJNI.new_CData(), true);
  }

}
