/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.zgzhu.rstptoyuvdemo;

public class RtspDecodeClient {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RtspDecodeClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RtspDecodeClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rtsp_decoderJNI.delete_RtspDecodeClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RtspDecodeClient() {
    this(rtsp_decoderJNI.new_RtspDecodeClient(), true);
  }

  public void OpenUrl(String progName, String rtspUrl) {
    rtsp_decoderJNI.RtspDecodeClient_OpenUrl(swigCPtr, this, progName, rtspUrl);
  }

  public void GetNALU(CData data) {
    rtsp_decoderJNI.RtspDecodeClient_GetNALU(swigCPtr, this, CData.getCPtr(data), data);
  }

  public void setMpUnit(String value) {
    rtsp_decoderJNI.RtspDecodeClient_mpUnit_set(swigCPtr, this, value);
  }

  public String getMpUnit() {
    return rtsp_decoderJNI.RtspDecodeClient_mpUnit_get(swigCPtr, this);
  }

  public void setMpSink(SWIGTYPE_p_RtspDecodeSink value) {
    rtsp_decoderJNI.RtspDecodeClient_mpSink_set(swigCPtr, this, SWIGTYPE_p_RtspDecodeSink.getCPtr(value));
  }

  public SWIGTYPE_p_RtspDecodeSink getMpSink() {
    long cPtr = rtsp_decoderJNI.RtspDecodeClient_mpSink_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_RtspDecodeSink(cPtr, false);
  }

  public void setMBuffer(String value) {
    rtsp_decoderJNI.RtspDecodeClient_mBuffer_set(swigCPtr, this, value);
  }

  public String getMBuffer() {
    return rtsp_decoderJNI.RtspDecodeClient_mBuffer_get(swigCPtr, this);
  }

  public void setMBufferPos(int value) {
    rtsp_decoderJNI.RtspDecodeClient_mBufferPos_set(swigCPtr, this, value);
  }

  public int getMBufferPos() {
    return rtsp_decoderJNI.RtspDecodeClient_mBufferPos_get(swigCPtr, this);
  }

  public void setMReadyToSend(boolean value) {
    rtsp_decoderJNI.RtspDecodeClient_mReadyToSend_set(swigCPtr, this, value);
  }

  public boolean getMReadyToSend() {
    return rtsp_decoderJNI.RtspDecodeClient_mReadyToSend_get(swigCPtr, this);
  }

}
