/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.zgzhu.rstptoyuvdemo;

public class rtsp_decoderJNI {
  public final static native byte[] cdata(long jarg1, int jarg2);
  public final static native void memmove(long jarg1, byte[] jarg2);
  public final static native void CData_data_set(long jarg1, CData jarg1_, long jarg2);
  public final static native long CData_data_get(long jarg1, CData jarg1_);
  public final static native void CData_len_set(long jarg1, CData jarg1_, int jarg2);
  public final static native int CData_len_get(long jarg1, CData jarg1_);
  public final static native long new_CData();
  public final static native void delete_CData(long jarg1);
  public final static native long new_RtspDecodeClient();
  public final static native void delete_RtspDecodeClient(long jarg1);
  public final static native void RtspDecodeClient_OpenUrl(long jarg1, RtspDecodeClient jarg1_, String jarg2, String jarg3);
  public final static native void RtspDecodeClient_GetNALU(long jarg1, RtspDecodeClient jarg1_, long jarg2, CData jarg2_);
  public final static native void RtspDecodeClient_mpUnit_set(long jarg1, RtspDecodeClient jarg1_, String jarg2);
  public final static native String RtspDecodeClient_mpUnit_get(long jarg1, RtspDecodeClient jarg1_);
  public final static native void RtspDecodeClient_mpSink_set(long jarg1, RtspDecodeClient jarg1_, long jarg2);
  public final static native long RtspDecodeClient_mpSink_get(long jarg1, RtspDecodeClient jarg1_);
  public final static native void RtspDecodeClient_mBuffer_set(long jarg1, RtspDecodeClient jarg1_, String jarg2);
  public final static native String RtspDecodeClient_mBuffer_get(long jarg1, RtspDecodeClient jarg1_);
  public final static native void RtspDecodeClient_mBufferPos_set(long jarg1, RtspDecodeClient jarg1_, int jarg2);
  public final static native int RtspDecodeClient_mBufferPos_get(long jarg1, RtspDecodeClient jarg1_);
  public final static native void RtspDecodeClient_mReadyToSend_set(long jarg1, RtspDecodeClient jarg1_, boolean jarg2);
  public final static native boolean RtspDecodeClient_mReadyToSend_get(long jarg1, RtspDecodeClient jarg1_);
}
