/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <string>


typedef struct SWIGCDATA {
    char *data;
    int   len;
} SWIGCDATA;



static SWIGCDATA cdata_void(void *ptr, int nelements) {



   SWIGCDATA d;
   d.data = (char *) ptr;



   d.len  = nelements;

   return d;
}


static jbyteArray SWIG_JavaArrayOutCDATA(JNIEnv *jenv, char *result, jsize sz) {
  jbyte *arr;
  int i;
  jbyteArray jresult = jenv->NewByteArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetByteArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  jenv->ReleaseByteArrayElements(jresult, arr, 0);
  return jresult;
}


#include "rtsp_decode_client.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jbyteArray JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_cdata(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jbyteArray jresult = 0 ;
  void *arg1 = (void *) 0 ;
  int arg2 ;
  SWIGCDATA result;
  
  (void)jenv;
  (void)jcls;
  arg2 = 1;
  arg1 = *(void **)&jarg1; 
  arg2 = (int)jarg2; 
  result = cdata_void(arg1,arg2);
  jresult = SWIG_JavaArrayOutCDATA(jenv, (char *)(&result)->data, (&result)->len); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_memmove(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2) {
  void *arg1 = (void *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  {
    if (jarg2) {
      arg2 = (char *) jenv->GetByteArrayElements(jarg2, 0);
      arg3 = (size_t) jenv->GetArrayLength(jarg2);
    } else {
      arg2 = 0;
      arg3 = 0;
    }
  }
  memmove(arg1,(void const *)arg2,arg3);
  {
    if (jarg2) jenv->ReleaseByteArrayElements(jarg2, (jbyte *)arg2, 0);
  }
  
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_CData_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  CData *arg1 = (CData *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CData **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->data = (void const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_CData_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CData *arg1 = (CData *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CData **)&jarg1; 
  result = (void *) ((arg1)->data);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_CData_1len_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  CData *arg1 = (CData *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CData **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->len = arg2;
}


SWIGEXPORT jint JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_CData_1len_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  CData *arg1 = (CData *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CData **)&jarg1; 
  result = (int) ((arg1)->len);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_new_1CData(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CData *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CData *)new CData();
  *(CData **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_delete_1CData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CData *arg1 = (CData *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CData **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_new_1RtspDecodeClient(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  RtspDecodeClient *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (RtspDecodeClient *)new RtspDecodeClient();
  *(RtspDecodeClient **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_delete_1RtspDecodeClient(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1OpenUrl(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return ;
  }
  (arg1)->OpenUrl((char const *)arg2,(char const *)arg3);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1GetNALU(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  CData *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  arg2 = *(CData **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CData & reference is null");
    return ;
  } 
  (arg1)->GetNALU(*arg2);
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mpUnit_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    delete [] arg1->mpUnit;
    if (arg2) {
      arg1->mpUnit = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->mpUnit, (const char *)arg2);
    } else {
      arg1->mpUnit = 0;
    }
  }
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mpUnit_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  result = (char *) ((arg1)->mpUnit);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mpSink_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  RtspDecodeSink *arg2 = (RtspDecodeSink *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  arg2 = *(RtspDecodeSink **)&jarg2; 
  if (arg1) (arg1)->mpSink = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mpSink_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  RtspDecodeSink *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  result = (RtspDecodeSink *) ((arg1)->mpSink);
  *(RtspDecodeSink **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mBuffer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    delete [] arg1->mBuffer;
    if (arg2) {
      arg1->mBuffer = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->mBuffer, (const char *)arg2);
    } else {
      arg1->mBuffer = 0;
    }
  }
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mBuffer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  result = (char *) ((arg1)->mBuffer);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mBufferPos_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->mBufferPos = arg2;
}


SWIGEXPORT jint JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mBufferPos_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  result = (int) ((arg1)->mBufferPos);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mReadyToSend_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->mReadyToSend = arg2;
}


SWIGEXPORT jboolean JNICALL Java_com_example_zgzhu_rstptoyuvdemo_rtsp_1decoderJNI_RtspDecodeClient_1mReadyToSend_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  RtspDecodeClient *arg1 = (RtspDecodeClient *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(RtspDecodeClient **)&jarg1; 
  result = (bool) ((arg1)->mReadyToSend);
  jresult = (jboolean)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

