/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.zgzhu.rstptoyuvdemo;

public class rtsp_decoder {
  public static byte[] cdata(SWIGTYPE_p_void ptr, int nelements) {
    return rtsp_decoderJNI.cdata(SWIGTYPE_p_void.getCPtr(ptr), nelements);
  }

  public static void memmove(SWIGTYPE_p_void data, byte[] indata) {
    rtsp_decoderJNI.memmove(SWIGTYPE_p_void.getCPtr(data), indata);
  }

}
